<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251120153302 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, is_released BOOLEAN NOT NULL, type VARCHAR(255) NOT NULL, source TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE document_overlay (document_id INT NOT NULL, overlay_id INT NOT NULL, PRIMARY KEY (document_id, overlay_id))');
        $this->addSql('CREATE INDEX IDX_1D909A62C33F7837 ON document_overlay (document_id)');
        $this->addSql('CREATE INDEX IDX_1D909A62F77080E1 ON document_overlay (overlay_id)');
        $this->addSql('CREATE TABLE overlay (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, is_released BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE overlay_project (overlay_id INT NOT NULL, project_id INT NOT NULL, PRIMARY KEY (overlay_id, project_id))');
        $this->addSql('CREATE INDEX IDX_E57FB89F77080E1 ON overlay_project (overlay_id)');
        $this->addSql('CREATE INDEX IDX_E57FB89166D1F9C ON overlay_project (project_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, is_released BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE document_overlay ADD CONSTRAINT FK_1D909A62C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_overlay ADD CONSTRAINT FK_1D909A62F77080E1 FOREIGN KEY (overlay_id) REFERENCES overlay (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE overlay_project ADD CONSTRAINT FK_E57FB89F77080E1 FOREIGN KEY (overlay_id) REFERENCES overlay (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE overlay_project ADD CONSTRAINT FK_E57FB89166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document_overlay DROP CONSTRAINT FK_1D909A62C33F7837');
        $this->addSql('ALTER TABLE document_overlay DROP CONSTRAINT FK_1D909A62F77080E1');
        $this->addSql('ALTER TABLE overlay_project DROP CONSTRAINT FK_E57FB89F77080E1');
        $this->addSql('ALTER TABLE overlay_project DROP CONSTRAINT FK_E57FB89166D1F9C');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE document_overlay');
        $this->addSql('DROP TABLE overlay');
        $this->addSql('DROP TABLE overlay_project');
        $this->addSql('DROP TABLE project');
    }
}
